### PR TITLE
Use standard test and benchmark harnesses, and criterion for testing

### PR DESCRIPTION
**Pull request by urschrei**
This PR simplifies the benchmarks, adds a "standard" test that mimics the benchmark while ensuring that the results match, and simplifies the geometry + index setup.

Run tests with `cargo test`
Run benchmarks with `cargo bench`

The benchmark moves the r-tree creation logic outside the measurement harness which may be controversial but my thinking is that the cost of creating the r-tree (around 2.5 ms on my machine) isn't really relevant here:  the only reason to create one is in order to perform multiple queries against it, so the cost is amortized anyway.

### CODE REVIEW

**Comment by urschrei** [comment]
The benchmarks now demonstrate the source of most of the time: the geometry at index 52.

This is demonstrated by the perf difference between the `Known to intersect` and `Known to intersect, including slow check` benchmarks, which differ only by the addition of the geom at index 52.

**Comment by JosiahParry** [comment]
FWIW this is what the polygon looks like 
image

**Comment by urschrei** [comment]
Using the new intersection check on `main` results in a 62 % time reduction, with the intersection check for index 52 now taking around 3.7 ms:

pdf

pdf

pdf

pdf

**Comment by JosiahParry** [comment]
Amazing!

**Pull request closed without merging**
